[2024-06-22T22:09:43.277+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: transform_data_dag.get_data manual__2024-06-22T22:08:58.123401+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
