[2024-06-24T02:29:31.796+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T02:29:31.893+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_DAG.trigger_encrypt_upload_dag manual__2024-06-24T02:28:57.191183+00:00 [queued]>
[2024-06-24T02:29:31.913+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_DAG.trigger_encrypt_upload_dag manual__2024-06-24T02:28:57.191183+00:00 [queued]>
[2024-06-24T02:29:31.914+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-24T02:29:31.946+0000] {taskinstance.py:2330} INFO - Executing <Task(TriggerDagRunOperator): trigger_encrypt_upload_dag> on 2024-06-24 02:28:57.191183+00:00
[2024-06-24T02:29:31.959+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=701) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T02:29:31.961+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG', 'trigger_encrypt_upload_dag', 'manual__2024-06-24T02:28:57.191183+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmpmp6kd4n1']
[2024-06-24T02:29:31.963+0000] {standard_task_runner.py:63} INFO - Started process 702 to run task
[2024-06-24T02:29:31.963+0000] {standard_task_runner.py:91} INFO - Job 183: Subtask trigger_encrypt_upload_dag
[2024-06-24T02:29:32.049+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_DAG.trigger_encrypt_upload_dag manual__2024-06-24T02:28:57.191183+00:00 [running]> on host f4301f0367ea
[2024-06-24T02:29:32.239+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_DAG' AIRFLOW_CTX_TASK_ID='trigger_encrypt_upload_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T02:28:57.191183+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T02:28:57.191183+00:00'
[2024-06-24T02:29:32.242+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T02:29:32.319+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T02:29:32.334+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 177, in execute
    dag_run = trigger_dag(
              ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api/common/trigger_dag.py", line 123, in trigger_dag
    raise DagNotFound(f"Dag id {dag_id} not found in DagModel")
airflow.exceptions.DagNotFound: Dag id transforma_carga_bigquery not found in DagModel
[2024-06-24T02:29:32.352+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_DAG, task_id=trigger_encrypt_upload_dag, run_id=manual__2024-06-24T02:28:57.191183+00:00, execution_date=20240624T022857, start_date=20240624T022931, end_date=20240624T022932
[2024-06-24T02:29:32.377+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 183 for task trigger_encrypt_upload_dag (Dag id transforma_carga_bigquery not found in DagModel; 702)
[2024-06-24T02:29:32.428+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T02:29:32.507+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T02:29:32.531+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
