[2024-06-23T01:40:12.773+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_pipeline_dag.delete_table manual__2024-06-23T01:39:47.446061+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
