[2024-06-23T22:44:51.986+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T22:44:52.010+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T22:39:10.289271+00:00 [queued]>
[2024-06-23T22:44:52.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T22:39:10.289271+00:00 [queued]>
[2024-06-23T22:44:52.020+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-23T22:44:52.037+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): decrypt_transform_and_upload> on 2024-06-23 22:39:10.289271+00:00
[2024-06-23T22:44:52.053+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T22:44:52.055+0000] {standard_task_runner.py:63} INFO - Started process 305 to run task
[2024-06-23T22:44:52.056+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'decrypt_transform_upload_dag', 'decrypt_transform_and_upload', 'manual__2024-06-23T22:39:10.289271+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/desencrypt_upload.py', '--cfg-path', '/tmp/tmp14tufic9']
[2024-06-23T22:44:52.059+0000] {standard_task_runner.py:91} INFO - Job 142: Subtask decrypt_transform_and_upload
[2024-06-23T22:44:52.341+0000] {task_command.py:426} INFO - Running <TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T22:39:10.289271+00:00 [running]> on host 0c896a61bf45
[2024-06-23T22:44:52.447+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='decrypt_transform_upload_dag' AIRFLOW_CTX_TASK_ID='decrypt_transform_and_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T22:39:10.289271+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T22:39:10.289271+00:00'
[2024-06-23T22:44:52.448+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T22:44:52.474+0000] {desencrypt_upload.py:51} INFO - Starting decryption and transformation process...
[2024-06-23T22:44:52.488+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T22:44:52.491+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T22:44:53.456+0000] {desencrypt_upload.py:58} INFO - File downloaded from GCS: datasets/athletes.csv.enc
[2024-06-23T22:44:54.958+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T22:44:54.959+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T22:44:56.385+0000] {desencrypt_upload.py:108} ERROR - An error occurred during the decryption, transformation and upload process
Traceback (most recent call last):
  File "/opt/airflow/dags/desencrypt_upload.py", line 97, in task_decrypt_transform_and_upload
    bq_hook.insert_rows(
TypeError: BigQueryHook.insert_rows() missing 1 required positional argument: 'table'
[2024-06-23T22:44:56.390+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T22:44:56.391+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/desencrypt_upload.py", line 97, in task_decrypt_transform_and_upload
    bq_hook.insert_rows(
TypeError: BigQueryHook.insert_rows() missing 1 required positional argument: 'table'
[2024-06-23T22:44:56.406+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=decrypt_transform_upload_dag, task_id=decrypt_transform_and_upload, run_id=manual__2024-06-23T22:39:10.289271+00:00, execution_date=20240623T223910, start_date=20240623T224452, end_date=20240623T224456
[2024-06-23T22:44:56.426+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 142 for task decrypt_transform_and_upload (BigQueryHook.insert_rows() missing 1 required positional argument: 'table'; 305)
[2024-06-23T22:44:56.455+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T22:44:56.473+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T22:44:56.476+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
