[2024-06-23T22:02:02.376+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T22:02:02.404+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T21:54:53.112489+00:00 [queued]>
[2024-06-23T22:02:02.420+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T21:54:53.112489+00:00 [queued]>
[2024-06-23T22:02:02.421+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-23T22:02:02.443+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): decrypt_transform_and_upload> on 2024-06-23 21:54:53.112489+00:00
[2024-06-23T22:02:02.469+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=653) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T22:02:02.471+0000] {standard_task_runner.py:63} INFO - Started process 667 to run task
[2024-06-23T22:02:02.472+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'decrypt_transform_upload_dag', 'decrypt_transform_and_upload', 'manual__2024-06-23T21:54:53.112489+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/desencrypt_upload.py', '--cfg-path', '/tmp/tmpq1s9rc0p']
[2024-06-23T22:02:02.477+0000] {standard_task_runner.py:91} INFO - Job 130: Subtask decrypt_transform_and_upload
[2024-06-23T22:02:02.582+0000] {task_command.py:426} INFO - Running <TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T21:54:53.112489+00:00 [running]> on host be05a2506c57
[2024-06-23T22:02:02.735+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='decrypt_transform_upload_dag' AIRFLOW_CTX_TASK_ID='decrypt_transform_and_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T21:54:53.112489+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T21:54:53.112489+00:00'
[2024-06-23T22:02:02.736+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T22:02:02.762+0000] {desencrypt_upload.py:51} INFO - Starting decryption and transformation process...
[2024-06-23T22:02:02.773+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T22:02:02.777+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T22:02:05.061+0000] {desencrypt_upload.py:58} INFO - File downloaded from GCS: datasets/athletes.csv.enc
[2024-06-23T22:02:08.309+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T22:02:08.316+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T22:02:08.317+0000] {desencrypt_upload.py:109} ERROR - An error occurred during the decryption, transformation and upload process
Traceback (most recent call last):
  File "/opt/airflow/dags/desencrypt_upload.py", line 87, in task_decrypt_transform_and_upload
    bq_hook.create_empty_table(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 528, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BigQueryHook.create_empty_table() got an unexpected keyword argument 'clustering_fields'
[2024-06-23T22:02:08.331+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T22:02:08.332+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/desencrypt_upload.py", line 87, in task_decrypt_transform_and_upload
    bq_hook.create_empty_table(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 528, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BigQueryHook.create_empty_table() got an unexpected keyword argument 'clustering_fields'
[2024-06-23T22:02:08.705+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=decrypt_transform_upload_dag, task_id=decrypt_transform_and_upload, run_id=manual__2024-06-23T21:54:53.112489+00:00, execution_date=20240623T215453, start_date=20240623T220202, end_date=20240623T220208
[2024-06-23T22:02:08.798+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 130 for task decrypt_transform_and_upload (BigQueryHook.create_empty_table() got an unexpected keyword argument 'clustering_fields'; 667)
[2024-06-23T22:02:08.895+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T22:02:09.089+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T22:02:09.104+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
