[2024-06-23T22:13:31.145+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T22:13:31.163+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T22:13:21.582115+00:00 [queued]>
[2024-06-23T22:13:31.172+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T22:13:21.582115+00:00 [queued]>
[2024-06-23T22:13:31.173+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-23T22:13:31.191+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): decrypt_transform_and_upload> on 2024-06-23 22:13:21.582115+00:00
[2024-06-23T22:13:31.214+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T22:13:31.215+0000] {standard_task_runner.py:63} INFO - Started process 91 to run task
[2024-06-23T22:13:31.215+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'decrypt_transform_upload_dag', 'decrypt_transform_and_upload', 'manual__2024-06-23T22:13:21.582115+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/desencrypt_upload.py', '--cfg-path', '/tmp/tmpspe2xogr']
[2024-06-23T22:13:31.219+0000] {standard_task_runner.py:91} INFO - Job 134: Subtask decrypt_transform_and_upload
[2024-06-23T22:13:31.285+0000] {task_command.py:426} INFO - Running <TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T22:13:21.582115+00:00 [running]> on host be05a2506c57
[2024-06-23T22:13:31.407+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='decrypt_transform_upload_dag' AIRFLOW_CTX_TASK_ID='decrypt_transform_and_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T22:13:21.582115+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T22:13:21.582115+00:00'
[2024-06-23T22:13:31.409+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T22:13:31.436+0000] {desencrypt_upload.py:51} INFO - Starting decryption and transformation process...
[2024-06-23T22:13:31.448+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T22:13:31.451+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T22:13:32.984+0000] {desencrypt_upload.py:58} INFO - File downloaded from GCS: datasets/athletes.csv.enc
[2024-06-23T22:13:34.511+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T22:13:34.512+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T22:13:34.513+0000] {desencrypt_upload.py:109} ERROR - An error occurred during the decryption, transformation and upload process
Traceback (most recent call last):
  File "/opt/airflow/dags/desencrypt_upload.py", line 87, in task_decrypt_transform_and_upload
    bq_hook.create_empty_table(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 528, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BigQueryHook.create_empty_table() got an unexpected keyword argument 'clustering_fields'
[2024-06-23T22:13:34.518+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T22:13:34.519+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/desencrypt_upload.py", line 87, in task_decrypt_transform_and_upload
    bq_hook.create_empty_table(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 528, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BigQueryHook.create_empty_table() got an unexpected keyword argument 'clustering_fields'
[2024-06-23T22:13:34.533+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=decrypt_transform_upload_dag, task_id=decrypt_transform_and_upload, run_id=manual__2024-06-23T22:13:21.582115+00:00, execution_date=20240623T221321, start_date=20240623T221331, end_date=20240623T221334
[2024-06-23T22:13:34.557+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 134 for task decrypt_transform_and_upload (BigQueryHook.create_empty_table() got an unexpected keyword argument 'clustering_fields'; 91)
[2024-06-23T22:13:34.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T22:13:34.631+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T22:13:34.634+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
