[2024-06-24T04:46:56.891+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T04:46:56.913+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: encryption_dag.encrypt_and_upload manual__2024-06-24T04:46:50.344520+00:00 [queued]>
[2024-06-24T04:46:56.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: encryption_dag.encrypt_and_upload manual__2024-06-24T04:46:50.344520+00:00 [queued]>
[2024-06-24T04:46:56.923+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-24T04:46:56.940+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): encrypt_and_upload> on 2024-06-24 04:46:50.344520+00:00
[2024-06-24T04:46:56.954+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=710) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T04:46:56.956+0000] {standard_task_runner.py:63} INFO - Started process 723 to run task
[2024-06-24T04:46:56.957+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'encryption_dag', 'encrypt_and_upload', 'manual__2024-06-24T04:46:50.344520+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/encryption_dag.py', '--cfg-path', '/tmp/tmpabwdgssu']
[2024-06-24T04:46:56.960+0000] {standard_task_runner.py:91} INFO - Job 215: Subtask encrypt_and_upload
[2024-06-24T04:46:57.015+0000] {task_command.py:426} INFO - Running <TaskInstance: encryption_dag.encrypt_and_upload manual__2024-06-24T04:46:50.344520+00:00 [running]> on host 4e5646ae0bec
[2024-06-24T04:46:57.128+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='encryption_dag' AIRFLOW_CTX_TASK_ID='encrypt_and_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T04:46:50.344520+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T04:46:50.344520+00:00'
[2024-06-24T04:46:57.130+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T04:46:57.160+0000] {encryption_dag.py:44} INFO - Starting encryption process...
[2024-06-24T04:46:57.181+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-24T04:46:57.183+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-24T04:46:58.395+0000] {encryption_dag.py:51} INFO - File downloaded from GCS: datasets/athletes.csv
[2024-06-24T04:46:58.398+0000] {encryption_dag.py:66} ERROR - An error occurred during the encryption and upload process
Traceback (most recent call last):
  File "/opt/airflow/dags/encryption_dag.py", line 54, in task_encrypt_and_upload
    ciphertext = encrypt_data(source_data, key_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/encryption_dag.py", line 37, in encrypt_data
    response = kms_client.encrypt(request={'name': key_name, 'plaintext': data.encode('utf-8')})
                                                                          ^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?
[2024-06-24T04:46:58.404+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T04:46:58.405+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/encryption_dag.py", line 54, in task_encrypt_and_upload
    ciphertext = encrypt_data(source_data, key_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/encryption_dag.py", line 37, in encrypt_data
    response = kms_client.encrypt(request={'name': key_name, 'plaintext': data.encode('utf-8')})
                                                                          ^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?
[2024-06-24T04:46:58.449+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=encryption_dag, task_id=encrypt_and_upload, run_id=manual__2024-06-24T04:46:50.344520+00:00, execution_date=20240624T044650, start_date=20240624T044656, end_date=20240624T044658
[2024-06-24T04:46:58.470+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 215 for task encrypt_and_upload ('bytes' object has no attribute 'encode'; 723)
[2024-06-24T04:46:58.497+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T04:46:58.519+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T04:46:58.523+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
