[2024-06-23T22:55:46.292+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T22:55:46.309+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T22:55:42.600580+00:00 [queued]>
[2024-06-23T22:55:46.318+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T22:55:42.600580+00:00 [queued]>
[2024-06-23T22:55:46.319+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-23T22:55:46.335+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): decrypt_transform_and_upload> on 2024-06-23 22:55:42.600580+00:00
[2024-06-23T22:55:46.352+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=570) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T22:55:46.354+0000] {standard_task_runner.py:63} INFO - Started process 584 to run task
[2024-06-23T22:55:46.353+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'decrypt_transform_upload_dag', 'decrypt_transform_and_upload', 'manual__2024-06-23T22:55:42.600580+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/desencrypt_upload.py', '--cfg-path', '/tmp/tmpnlu5tpaq']
[2024-06-23T22:55:46.356+0000] {standard_task_runner.py:91} INFO - Job 146: Subtask decrypt_transform_and_upload
[2024-06-23T22:55:46.412+0000] {task_command.py:426} INFO - Running <TaskInstance: decrypt_transform_upload_dag.decrypt_transform_and_upload manual__2024-06-23T22:55:42.600580+00:00 [running]> on host 0c896a61bf45
[2024-06-23T22:55:46.511+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='decrypt_transform_upload_dag' AIRFLOW_CTX_TASK_ID='decrypt_transform_and_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T22:55:42.600580+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T22:55:42.600580+00:00'
[2024-06-23T22:55:46.512+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T22:55:46.539+0000] {desencrypt_upload.py:51} INFO - Starting decryption and transformation process...
[2024-06-23T22:55:46.550+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T22:55:46.554+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T22:55:47.361+0000] {desencrypt_upload.py:58} INFO - File downloaded from GCS: datasets/athletes.csv.enc
[2024-06-23T22:55:48.543+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-23T22:55:48.544+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-23T22:55:48.551+0000] {desencrypt_upload.py:81} ERROR - An error occurred during the decryption, transformation and upload process
Traceback (most recent call last):
  File "/opt/airflow/dags/desencrypt_upload.py", line 73, in task_decrypt_transform_and_upload
    bq_hook.insert_rows(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 297, in insert_rows
    raise NotImplementedError()
NotImplementedError
[2024-06-23T22:55:48.559+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T22:55:48.560+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/desencrypt_upload.py", line 73, in task_decrypt_transform_and_upload
    bq_hook.insert_rows(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 297, in insert_rows
    raise NotImplementedError()
NotImplementedError
[2024-06-23T22:55:48.574+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=decrypt_transform_upload_dag, task_id=decrypt_transform_and_upload, run_id=manual__2024-06-23T22:55:42.600580+00:00, execution_date=20240623T225542, start_date=20240623T225546, end_date=20240623T225548
[2024-06-23T22:55:48.595+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 146 for task decrypt_transform_and_upload (; 584)
[2024-06-23T22:55:48.620+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T22:55:48.640+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T22:55:48.643+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
