[2024-06-22T06:05:47.411+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-22T06:05:47.428+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_processing.etl_process scheduled__2024-06-21T00:00:00+00:00 [queued]>
[2024-06-22T06:05:47.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_processing.etl_process scheduled__2024-06-21T00:00:00+00:00 [queued]>
[2024-06-22T06:05:47.438+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-22T06:05:47.453+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): etl_process> on 2024-06-21 00:00:00+00:00
[2024-06-22T06:05:47.460+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1527) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-22T06:05:47.462+0000] {standard_task_runner.py:63} INFO - Started process 1528 to run task
[2024-06-22T06:05:47.462+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_processing', 'etl_process', 'scheduled__2024-06-21T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/gcs_processing.py', '--cfg-path', '/tmp/tmpzidxp8mo']
[2024-06-22T06:05:47.465+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask etl_process
[2024-06-22T06:05:47.522+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_processing.etl_process scheduled__2024-06-21T00:00:00+00:00 [running]> on host ef7fea064a97
[2024-06-22T06:05:47.613+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_processing' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-21T00:00:00+00:00'
[2024-06-22T06:05:47.615+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-22T06:05:47.642+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-22T06:05:47.644+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-22T06:05:47.645+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-22T06:05:47.646+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gcs_processing.py", line 11, in etl_process
    source_data = gcs_hook.download(bucket_name, source_blob)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 341, in download
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 332, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 371, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 245, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 295, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/service_account.py", line 258, in from_service_account_file
    info, signer = _service_account_info.from_filename(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Yerko\\Desktop\\Security Topics\\Airflow\\dags\\keys\\boreal-forest-427103-q9-fc0cdec7fd29.json'
[2024-06-22T06:05:47.670+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_processing, task_id=etl_process, run_id=scheduled__2024-06-21T00:00:00+00:00, execution_date=20240621T000000, start_date=20240622T060547, end_date=20240622T060547
[2024-06-22T06:05:47.684+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task etl_process ([Errno 2] No such file or directory: 'C:\\Users\\Yerko\\Desktop\\Security Topics\\Airflow\\dags\\keys\\boreal-forest-427103-q9-fc0cdec7fd29.json'; 1528)
[2024-06-22T06:05:47.718+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-22T06:05:47.734+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-22T06:05:47.737+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-22T06:31:28.662+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-22T06:31:28.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_processing.etl_process scheduled__2024-06-21T00:00:00+00:00 [queued]>
[2024-06-22T06:31:28.697+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_processing.etl_process scheduled__2024-06-21T00:00:00+00:00 [queued]>
[2024-06-22T06:31:28.698+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-22T06:31:28.715+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): etl_process> on 2024-06-21 00:00:00+00:00
[2024-06-22T06:31:28.737+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_processing', 'etl_process', 'scheduled__2024-06-21T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/gcs_processing.py', '--cfg-path', '/tmp/tmp_qm53v49']
[2024-06-22T06:31:28.736+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1836) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-22T06:31:28.743+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask etl_process
[2024-06-22T06:31:28.744+0000] {standard_task_runner.py:63} INFO - Started process 1837 to run task
[2024-06-22T06:31:28.879+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_processing.etl_process scheduled__2024-06-21T00:00:00+00:00 [running]> on host ef7fea064a97
[2024-06-22T06:31:29.009+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_processing' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-21T00:00:00+00:00'
[2024-06-22T06:31:29.011+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-22T06:31:29.060+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-22T06:31:29.079+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-22T06:31:29.080+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-22T06:31:29.095+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gcs_processing.py", line 15, in etl_process
    source_data = gcs_hook.download(bucket_name, source_blob)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 341, in download
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 332, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 371, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 217, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-06-22T06:31:29.112+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_processing, task_id=etl_process, run_id=scheduled__2024-06-21T00:00:00+00:00, execution_date=20240621T000000, start_date=20240622T063128, end_date=20240622T063129
[2024-06-22T06:31:29.133+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task etl_process (The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 1837)
[2024-06-22T06:31:29.160+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-22T06:31:29.187+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-22T06:31:29.190+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
