[2024-06-23T02:56:16.983+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_pipeline_dag_with_encryption.delete_table manual__2024-06-23T02:55:34.495783+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
