[2024-06-22T06:22:31.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-22T06:22:31.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_processing.etl_process manual__2024-06-22T06:22:28.067622+00:00 [queued]>
[2024-06-22T06:22:31.285+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_processing.etl_process manual__2024-06-22T06:22:28.067622+00:00 [queued]>
[2024-06-22T06:22:31.287+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-22T06:22:31.302+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): etl_process> on 2024-06-22 06:22:28.067622+00:00
[2024-06-22T06:22:31.311+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1734) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-22T06:22:31.313+0000] {standard_task_runner.py:63} INFO - Started process 1735 to run task
[2024-06-22T06:22:31.312+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_processing', 'etl_process', 'manual__2024-06-22T06:22:28.067622+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/gcs_processing.py', '--cfg-path', '/tmp/tmpjzwv8g29']
[2024-06-22T06:22:31.315+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask etl_process
[2024-06-22T06:22:31.371+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_processing.etl_process manual__2024-06-22T06:22:28.067622+00:00 [running]> on host ef7fea064a97
[2024-06-22T06:22:31.468+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_processing' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T06:22:28.067622+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T06:22:28.067622+00:00'
[2024-06-22T06:22:31.469+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-22T06:22:31.509+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-22T06:22:31.514+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-22T06:22:31.516+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-22T06:22:31.526+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gcs_processing.py", line 11, in etl_process
    source_data = gcs_hook.download(bucket_name, source_blob)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 341, in download
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 332, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 371, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 217, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-06-22T06:22:31.568+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_processing, task_id=etl_process, run_id=manual__2024-06-22T06:22:28.067622+00:00, execution_date=20240622T062228, start_date=20240622T062231, end_date=20240622T062231
[2024-06-22T06:22:31.585+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task etl_process (The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 1735)
[2024-06-22T06:22:31.609+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-22T06:22:31.630+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-22T06:22:31.634+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
